/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FamilyPortalRouteImport } from './routes/family-portal'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminServiceAreasRouteImport } from './routes/admin.service-areas'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminConsultationsRouteImport } from './routes/admin.consultations'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminServicesIndexRouteImport } from './routes/admin.services.index'
import { Route as AdminServicesIdRouteImport } from './routes/admin.services.$id'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyPortalRoute = FamilyPortalRouteImport.update({
  id: '/family-portal',
  path: '/family-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServiceAreasRoute = AdminServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConsultationsRoute = AdminConsultationsRouteImport.update({
  id: '/consultations',
  path: '/consultations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesIndexRoute = AdminServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminServicesRoute,
} as any)
const AdminServicesIdRoute = AdminServicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/consultation': typeof ConsultationRoute
  '/family-portal': typeof FamilyPortalRoute
  '/login': typeof LoginRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/blog': typeof AdminBlogRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/service-areas': typeof AdminServiceAreasRoute
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/services/$id': typeof AdminServicesIdRoute
  '/admin/services/': typeof AdminServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/family-portal': typeof FamilyPortalRoute
  '/login': typeof LoginRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/blog': typeof AdminBlogRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/service-areas': typeof AdminServiceAreasRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/services/$id': typeof AdminServicesIdRoute
  '/admin/services': typeof AdminServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/consultation': typeof ConsultationRoute
  '/family-portal': typeof FamilyPortalRoute
  '/login': typeof LoginRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/blog': typeof AdminBlogRoute
  '/admin/consultations': typeof AdminConsultationsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/service-areas': typeof AdminServiceAreasRoute
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/services/$id': typeof AdminServicesIdRoute
  '/admin/services/': typeof AdminServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/consultation'
    | '/family-portal'
    | '/login'
    | '/resources'
    | '/services'
    | '/admin/blog'
    | '/admin/consultations'
    | '/admin/faqs'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/seo'
    | '/admin/service-areas'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/subscribers'
    | '/admin/testimonials'
    | '/services/$slug'
    | '/admin/'
    | '/admin/services/$id'
    | '/admin/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/consultation'
    | '/family-portal'
    | '/login'
    | '/resources'
    | '/services'
    | '/admin/blog'
    | '/admin/consultations'
    | '/admin/faqs'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/seo'
    | '/admin/service-areas'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/subscribers'
    | '/admin/testimonials'
    | '/services/$slug'
    | '/admin'
    | '/admin/services/$id'
    | '/admin/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/consultation'
    | '/family-portal'
    | '/login'
    | '/resources'
    | '/services'
    | '/admin/blog'
    | '/admin/consultations'
    | '/admin/faqs'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/seo'
    | '/admin/service-areas'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/subscribers'
    | '/admin/testimonials'
    | '/services/$slug'
    | '/admin/'
    | '/admin/services/$id'
    | '/admin/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ConsultationRoute: typeof ConsultationRoute
  FamilyPortalRoute: typeof FamilyPortalRoute
  LoginRoute: typeof LoginRoute
  ResourcesRoute: typeof ResourcesRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-portal': {
      id: '/family-portal'
      path: '/family-portal'
      fullPath: '/family-portal'
      preLoaderRoute: typeof FamilyPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/service-areas': {
      id: '/admin/service-areas'
      path: '/service-areas'
      fullPath: '/admin/service-areas'
      preLoaderRoute: typeof AdminServiceAreasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/consultations': {
      id: '/admin/consultations'
      path: '/consultations'
      fullPath: '/admin/consultations'
      preLoaderRoute: typeof AdminConsultationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services/': {
      id: '/admin/services/'
      path: '/'
      fullPath: '/admin/services/'
      preLoaderRoute: typeof AdminServicesIndexRouteImport
      parentRoute: typeof AdminServicesRoute
    }
    '/admin/services/$id': {
      id: '/admin/services/$id'
      path: '/$id'
      fullPath: '/admin/services/$id'
      preLoaderRoute: typeof AdminServicesIdRouteImport
      parentRoute: typeof AdminServicesRoute
    }
  }
}

interface AdminServicesRouteChildren {
  AdminServicesIdRoute: typeof AdminServicesIdRoute
  AdminServicesIndexRoute: typeof AdminServicesIndexRoute
}

const AdminServicesRouteChildren: AdminServicesRouteChildren = {
  AdminServicesIdRoute: AdminServicesIdRoute,
  AdminServicesIndexRoute: AdminServicesIndexRoute,
}

const AdminServicesRouteWithChildren = AdminServicesRoute._addFileChildren(
  AdminServicesRouteChildren,
)

interface AdminRouteChildren {
  AdminBlogRoute: typeof AdminBlogRoute
  AdminConsultationsRoute: typeof AdminConsultationsRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminServiceAreasRoute: typeof AdminServiceAreasRoute
  AdminServicesRoute: typeof AdminServicesRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogRoute: AdminBlogRoute,
  AdminConsultationsRoute: AdminConsultationsRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminServiceAreasRoute: AdminServiceAreasRoute,
  AdminServicesRoute: AdminServicesRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ConsultationRoute: ConsultationRoute,
  FamilyPortalRoute: FamilyPortalRoute,
  LoginRoute: LoginRoute,
  ResourcesRoute: ResourcesRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
